image: maven:3.8.6-openjdk-18

services:
  - docker:dind
variables:
  MAVEN_OPTS: -DskipTests -Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true
  MAVEN_CLI_OPTS: --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true
  DOCKER_DRIVER: overlay
cache:
  paths:
    - .m2
stages:
  - build
  - package
  - deploy
build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean deploy -DskipTests
  artifacts:
    paths:
      - target/*.jar

